In [8]:
from statsbombpy import sb
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbn

In [9]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

In [10]:
comps = sb.competitions()

c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [11]:
comps[comps["competition_name"] == "La Liga"].head(18)

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
40,11,90,Spain,La Liga,male,False,False,2020/2021,2025-11-02T03:55:19.577958,2025-11-02T03:55:53.923193,2025-11-02T03:55:53.923193,2025-11-02T03:55:19.577958
41,11,42,Spain,La Liga,male,False,False,2019/2020,2024-12-16T16:51:06.833054,2021-06-13T16:17:31.694,NaN,2024-12-16T16:51:06.833054
42,11,4,Spain,La Liga,male,False,False,2018/2019,2026-04-06T04:49:09.959011,2021-07-09T14:53:22.103024,NaN,2026-04-06T04:49:09.959011
43,11,1,Spain,La Liga,male,False,False,2017/2018,2025-07-14T10:01:16.674864,2021-06-13T16:17:31.694,NaN,2025-07-14T10:01:16.674864
44,11,2,Spain,La Liga,male,False,False,2016/2017,2025-03-09T16:03:54.962718,2021-06-13T16:17:31.694,NaN,2025-03-09T16:03:54.962718
45,11,27,Spain,La Liga,male,False,False,2015/2016,2025-04-23T13:59:22.835792,2021-06-13T16:17:31.694,NaN,2025-04-23T13:59:22.835792
46,11,26,Spain,La Liga,male,False,False,2014/2015,2025-06-24T13:39:01.068680,2021-06-13T16:17:31.694,NaN,2025-06-24T13:39:01.068680
47,11,25,Spain,La Liga,male,False,False,2013/2014,2025-06-24T09:52:44.048585,2021-06-13T16:17:31.694,NaN,2025-06-24T09:52:44.048585
48,11,24,Spain,La Liga,male,False,False,2012/2013,2025-06-24T13:53:14.047130,2021-06-13T16:17:31.694,NaN,2025-06-24T13:53:14.047130
49,11,23,Spain,La Liga,male,False,False,2011/2012,2025-06-24T13:38:10.764259,2021-06-13T16:17:31.694,NaN,2025-06-24T13:38:10.764259
50,11,22,Spain,La Liga,male,False,False,2010/2011,2025-06-24T13:51:54.910296,2021-06-13T16:17:31.694,NaN,2025-06-24T13:51:54.910296
51,11,21,Spain,La Liga,male,False,False,2009/2010,2025-06-24T13:43:36.379754,2021-06-13T16:17:31.694,NaN,2025-06-24T13:43:36.379754
52,11,41,Spain,La Liga,male,False,False,2008/2009,2025-09-08T13:42:24.627088,2021-06-13T16:17:31.694,NaN,2025-09-08T13:42:24.627088
53,11,40,Spain,La Liga,male,False,False,2007/2008,2026-05-26T13:35:19.781918,2021-06-13T16:17:31.694,NaN,2025-08-15T14:05:12.751913
54,11,39,Spain,La Liga,male,False,False,2006/2007,2025-06-24T13:52:50.824119,2021-06-13T16:17:31.694,NaN,2025-06-24T13:52:50.824119
55,11,38,Spain,La Liga,male,False,False,2005/2006,2025-06-24T14:05:07.849675,2021-06-13T16:17:31.694,NaN,2025-06-24T14:05:07.849675
56,11,37,Spain,La Liga,male,False,False,2004/2005,2025-06-24T13:48:43.998096,2021-06-13T16:17:31.694,NaN,2025-06-24T13:48:43.998096
57,11,278,Spain,La Liga,male,False,False,1973/1974,2023-07-06T12:50:48.807820,NaN,NaN,2023-07-06T12:50:48.807820

In [12]:
la_liga = comps[comps["competition_name"] == "La Liga"]

In [13]:
la_liga.season_name

40    2020/2021
41    2019/2020
42    2018/2019
43    2017/2018
44    2016/2017
45    2015/2016
46    2014/2015
47    2013/2014
48    2012/2013
49    2011/2012
50    2010/2011
51    2009/2010
52    2008/2009
53    2007/2008
54    2006/2007
55    2005/2006
56    2004/2005
57    1973/1974
Name: season_name, dtype: str

In [14]:
print(len(la_liga))

18

In [15]:
la_liga_splited= []
for _, c in la_liga.iterrows():
    matches= sb.matches(competition_id=c["competition_id"], season_id=c["season_id"])
    la_liga_splited.append(matches)

la_liga_df= pd.concat(la_liga_splited, ignore_index=True)

c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [16]:
la_liga_df.shape

(867, 55)

In [17]:
barcelonas_matches=la_liga_df[(la_liga_df["home_team"] == "Barcelona") | (la_liga_df["away_team"]== "Barcelona")]

In [18]:
barcelonas_shots_splited= []
for _, event in barcelonas_matches.iterrows():
    barca_events= sb.events(match_id=event["match_id"])
    barca_shots= barca_events[barca_events["type"] == "Shot"]
    barcelonas_shots_splited.append(barca_shots)

barcelona_shots_df= pd.concat(barcelonas_shots_splited, ignore_index=True)

c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\danie\Documents\ML-Projects\football-predictions\.venv\Lib\site-packages\statsbombpy\api_client.py:27: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [19]:
barcelonas_matches.head()

,match_id,match_date,kick_off,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,match_week,competition_id,competition_country_name,competition_name,competition,season_id,season,home_team_id,home_team,home_team_gender,home_team_group,home_team_country_id,home_team_country_name,away_team_id,away_team,away_team_gender,away_team_group,away_team_country_id,away_team_country_name,competition_stage_id,competition_stage,stadium_id,stadium,stadium_country_id,stadium_country_name,referee_id,referee,referee_country_id,referee_country_name,home_managers,away_managers,home_manager_id,home_manager_name,home_manager_nickname,home_manager_dob,home_manager_country_id,home_manager_country_name,away_manager_id,away_manager_name,away_manager_nickname,away_manager_dob,away_manager_country_id,away_manager_country_name,data_version,shot_fidelity_version,xy_fidelity_version
0,3773386,2020-10-31,21:00:00.000,1,1,available,available,2023-07-25T03:54:59.280826,2023-07-25T04:25:41.348202,8,11,Spain,La Liga,Spain - La Liga,90,2020/2021,206,Deportivo Alavés,male,None,214,Spain,217,Barcelona,male,None,214,Spain,1,Regular Season,348,Estadio de Mendizorroza,214,Spain,NaN,NaN,NaN,NaN,Pablo Javier Machín Díez,Ronald Koeman,234,Pablo Javier Machín Díez,Pablo Machín,1975-04-07,214,Spain,676,Ronald Koeman,NaN,1963-03-21,160,Netherlands,1.1.0,2,2
1,3773565,2021-01-09,18:30:00.000,0,4,available,available,2023-07-25T03:51:37.437064,2023-07-25T04:30:16.058384,18,11,Spain,La Liga,Spain - La Liga,90,2020/2021,1049,Granada,male,None,214,Spain,217,Barcelona,male,None,214,Spain,1,Regular Season,4667,Estadio Nuevo Los Cármenes,214,Spain,2602.0,Ricardo De Burgos Bengoetxea,214.0,Spain,Diego Martínez Penas,Ronald Koeman,1597,Diego Martínez Penas,NaN,1980-12-16,214,Spain,676,Ronald Koeman,NaN,1963-03-21,160,Netherlands,1.1.0,2,2
2,3773457,2021-05-16,18:30:00.000,1,2,available,available,2022-12-02T09:26:39.496362,2023-04-27T23:03:53.506485,37,11,Spain,La Liga,Spain - La Liga,90,2020/2021,217,Barcelona,male,None,214,Spain,209,Celta Vigo,male,None,214,Spain,1,Regular Season,342,Spotify Camp Nou,214,Spain,NaN,NaN,NaN,NaN,Ronald Koeman,Eduardo Germán Coudet,676,Ronald Koeman,NaN,1963-03-21,160,Netherlands,2886,Eduardo Germán Coudet,Eduardo Coudet,1974-09-12,11,Argentina,1.1.0,2,2
3,3773631,2021-02-07,21:00:00.000,2,3,available,available,2023-07-25T03:47:44.278651,2023-07-25T03:56:34.733180,22,11,Spain,La Liga,Spain - La Liga,90,2020/2021,218,Real Betis,male,None,214,Spain,217,Barcelona,male,None,214,Spain,1,Regular Season,352,Estadio Benito Villamarín,214,Spain,NaN,NaN,NaN,NaN,Manuel Luis Pellegrini Ripamonti,Ronald Koeman,733,Manuel Luis Pellegrini Ripamonti,Manuel Pellegrini,1953-09-16,45,Chile,676,Ronald Koeman,NaN,1963-03-21,160,Netherlands,1.1.0,2,2
4,3773665,2021-03-06,21:00:00.000,0,2,available,available,2022-12-02T08:46:42.897589,2023-04-28T02:57:03.412841,26,11,Spain,La Liga,Spain - La Liga,90,2020/2021,422,Osasuna,male,None,214,Spain,217,Barcelona,male,None,214,Spain,1,Regular Season,4650,Estadio El Sadar,214,Spain,2402.0,Guillermo Cuadra Fernández,214.0,Spain,Jagoba Arrasate Elustondo,Ronald Koeman,1592,Jagoba Arrasate Elustondo,Jagoba Arrasate,1978-04-22,214,Spain,676,Ronald Koeman,NaN,1963-03-21,160,Netherlands,1.1.0,2,2

In [20]:
barcelonas_matches[barcelonas_matches["season"] == "1973/1974"]

,match_id,match_date,kick_off,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,match_week,competition_id,competition_country_name,competition_name,competition,season_id,season,home_team_id,home_team,home_team_gender,home_team_group,home_team_country_id,home_team_country_name,away_team_id,away_team,away_team_gender,away_team_group,away_team_country_id,away_team_country_name,competition_stage_id,competition_stage,stadium_id,stadium,stadium_country_id,stadium_country_name,referee_id,referee,referee_country_id,referee_country_name,home_managers,away_managers,home_manager_id,home_manager_name,home_manager_nickname,home_manager_dob,home_manager_country_id,home_manager_country_name,away_manager_id,away_manager_name,away_manager_nickname,away_manager_dob,away_manager_country_id,away_manager_country_name,data_version,shot_fidelity_version,xy_fidelity_version
866,3888713,1974-02-17,21:00:00.000,0,5,available,unscheduled,2023-07-06T12:50:48.807820,None,22,11,Spain,La Liga,Spain - La Liga,278,1973/1974,220,Real Madrid,male,None,214,Spain,217,Barcelona,male,None,214,Spain,1,Regular Season,353,Bernabéu,214,Spain,NaN,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.1.0,2,2

In [21]:
barcelona_shots_df.tail()

,50_50,bad_behaviour_card,ball_receipt_outcome,ball_recovery_offensive,ball_recovery_recovery_failure,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_right_foot,counterpress,dribble_nutmeg,dribble_outcome,dribble_overrun,duel_outcome,duel_type,duration,foul_committed_advantage,foul_committed_card,foul_committed_offensive,foul_committed_type,foul_won_advantage,foul_won_defensive,goalkeeper_body_part,goalkeeper_end_location,goalkeeper_outcome,goalkeeper_position,goalkeeper_technique,goalkeeper_type,id,index,interception_outcome,location,match_id,minute,miscontrol_aerial_won,off_camera,out,pass_aerial_won,pass_angle,pass_assisted_shot_id,pass_body_part,pass_cross,pass_cut_back,pass_deflected,pass_end_location,pass_height,pass_inswinging,pass_length,pass_no_touch,pass_outcome,pass_outswinging,pass_recipient,pass_recipient_id,pass_shot_assist,pass_switch,pass_technique,pass_through_ball,pass_type,period,play_pattern,player,player_id,position,possession,possession_team,possession_team_id,related_events,second,shot_aerial_won,shot_body_part,shot_end_location,shot_first_time,shot_freeze_frame,shot_key_pass_id,shot_one_on_one,shot_open_goal,shot_outcome,shot_statsbomb_xg,shot_technique,shot_type,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,tactics,team,team_id,timestamp,type,under_pressure,block_offensive,pass_goal_assist,pass_straight,block_deflection,clearance_other,shot_deflected,injury_stoppage_in_chain,pass_miscommunication,foul_committed_penalty,foul_won_penalty,goalkeeper_punched_out,goalkeeper_shot_saved_off_target,goalkeeper_shot_saved_to_post,shot_saved_off_target,shot_saved_to_post,block_save_block,dribble_no_touch,shot_redirect,shot_follows_dribble,goalkeeper_success_in_play,goalkeeper_lost_in_play,half_start_late_video_start,player_off_permanent,goalkeeper_lost_out,half_end_early_video_end,goalkeeper_success_out,goalkeeper_saved_to_post
12980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.250905,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5fa17856-9fcc-484e-9b2c-a5a87f475c73,2544,NaN,"[106.1, 51.5]",3888713,75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,Regular Play,Carles Rexach i Cerdà,397775.0,Right Wing,180,Barcelona,217,"[4b6b17f6-8dda-413b-a07b-21ea425acae9, 5826f9f...",17,NaN,Right Foot,"[109.6, 49.0]",NaN,"[{'location': ['100.4', '51.3'], 'player': {'i...",6c421284-586a-4d16-9be3-117357ba8066,NaN,NaN,Blocked,0.092134,Normal,Open Play,NaN,NaN,NaN,NaN,NaN,Barcelona,217,00:30:17.258,Shot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12981,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.944358,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6af58f7e-48b4-4d53-acc8-2109146ca66e,2557,NaN,"[109.9, 38.5]",3888713,75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,From Throw In,Hugo Alejandro Sotil Yerén,397776.0,Left Wing,181,Barcelona,217,"[1f5380c0-dc5b-4043-a74b-6d17cb2de560, d6ea767...",32,True,Head,"[120.0, 42.7, 3.3]",NaN,"[{'location': ['118.8', '38.8'], 'player': {'i...",c5eab3c1-6163-4957-a292-e22fb1acaa5a,NaN,NaN,Off T,0.108684,Normal,Open Play,NaN,NaN,NaN,NaN,NaN,Barcelona,217,00:30:32.013,Shot,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.398122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,df1ab8fe-ee57-4d40-8503-643762285469,2670,NaN,"[105.8, 59.9]",3888713,78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,From Counter,Carles Rexach i Cerdà,397775.0,Right Wing,191,Barcelona,217,[b252bd5b-1aca-418f-8b0d-189cd62ef922],55,NaN,Left Foot,"[115.0, 40.3]",NaN,"[{'location': ['118.5', '40.2'], 'player': {'i...",c202a8d9-3269-4de8-982d-73b2101ecefc,NaN,NaN,Wayward,0.011345,Normal,Open Play,NaN,NaN,NaN,NaN,NaN,Barcelona,217,00:33:55.517,Shot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.361332,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,d3c824f4-c9fc-40fb-8997-9377a8407ad2,2894,NaN,"[106.9, 29.2]",3888713,86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,From Throw In,Juan Manuel Asensi Ripoll,397774.0,Right Center Midfield,204,Barcelona,217,"[8265cb1e-9429-4e47-9152-0625455535b9, d05a123...",6,NaN,Left Foot,"[111.4, 33.0]",True,"[{'location': ['109.1', '44.1'], 'player': {'i...",a14162e7-22f2-4ef5-9431-58e17fa52ee7,NaN,NaN,Blocked,0.106139,Normal,Open Play,NaN,NaN,NaN,NaN,NaN,Barcelona,217,00:41:06.560,Shot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12984,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.202476,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7b3a4d12-08f6-4337-9000-a4303d9525cb,2911,NaN,"[100.2, 49.9]",3888713,86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,From Throw In,Johan Cruyff,39713.0,Center Forward,205,Barcelona,217,"[787bfa09-70f2-4030-a904-a8dcd7a95125, 9d78675...",34,NaN,Right Foot,"[103.1, 47.9]",NaN,"[{'location': ['88.5', '63.6'], 'player': {'id...",97e217bd-a841-4c6a-bf1c-951ba01f1a19,NaN,NaN,Blocked,0.044297,Half Volley,Open Play,NaN,NaN,NaN,NaN,NaN,Barcelona,217,00:41:34.666,Shot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
barcelona_shots_df.shape

(12985, 119)

In [23]:
barcelona_shots_df.to_csv("barcelona_shots.csv", index=False)

In [24]:
barca_df_shots = pd.read_csv("barcelona_shots.csv")

In [25]:
barca_df_shots.head()

,50_50,bad_behaviour_card,ball_receipt_outcome,ball_recovery_offensive,ball_recovery_recovery_failure,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_right_foot,counterpress,dribble_nutmeg,dribble_outcome,dribble_overrun,duel_outcome,duel_type,duration,foul_committed_advantage,foul_committed_card,foul_committed_offensive,foul_committed_type,foul_won_advantage,foul_won_defensive,goalkeeper_body_part,goalkeeper_end_location,goalkeeper_outcome,goalkeeper_position,goalkeeper_technique,goalkeeper_type,id,index,interception_outcome,location,match_id,minute,miscontrol_aerial_won,off_camera,out,pass_aerial_won,pass_angle,pass_assisted_shot_id,pass_body_part,pass_cross,pass_cut_back,pass_deflected,pass_end_location,pass_height,pass_inswinging,pass_length,pass_no_touch,pass_outcome,pass_outswinging,pass_recipient,pass_recipient_id,pass_shot_assist,pass_switch,pass_technique,pass_through_ball,pass_type,period,play_pattern,player,player_id,position,possession,possession_team,possession_team_id,related_events,second,shot_aerial_won,shot_body_part,shot_end_location,shot_first_time,shot_freeze_frame,shot_key_pass_id,shot_one_on_one,shot_open_goal,shot_outcome,shot_statsbomb_xg,shot_technique,shot_type,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,tactics,team,team_id,timestamp,type,under_pressure,block_offensive,pass_goal_assist,pass_straight,block_deflection,clearance_other,shot_deflected,injury_stoppage_in_chain,pass_miscommunication,foul_committed_penalty,foul_won_penalty,goalkeeper_punched_out,goalkeeper_shot_saved_off_target,goalkeeper_shot_saved_to_post,shot_saved_off_target,shot_saved_to_post,block_save_block,dribble_no_touch,shot_redirect,shot_follows_dribble,goalkeeper_success_in_play,goalkeeper_lost_in_play,half_start_late_video_start,player_off_permanent,goalkeeper_lost_out,half_end_early_video_end,goalkeeper_success_out,goalkeeper_saved_to_post
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.882096,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,c5341577-e1ca-4742-98fb-dc745cbbe103,575,NaN,"[108.6, 28.0]",3773386,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,From Throw In,Anssumane Fati,30756.0,Left Wing,27,Barcelona,217,['ce9cfc1e-f43c-41db-9f5c-8440b1341480'],19,NaN,Right Foot,"[120.0, 47.8, 0.0]",NaN,"[{'location': [91.6, 30.4], 'player': {'id': 5...",92f50ac4-2f1c-4221-9a5f-92b4911c26a6,True,NaN,Off T,0.200969,Normal,Open Play,NaN,NaN,NaN,NaN,NaN,Barcelona,217,00:12:19.834,Shot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.446744,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1aedaf9e-bc12-4d0a-953d-bd0f7db3688a,681,NaN,"[103.6, 51.0]",3773386,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Regular Play,Edgar Antonio Méndez Ortega,26387.0,Right Midfield,36,Deportivo Alavés,206,['a6cd82b1-65f1-4518-9a4e-b1220214c3c0'],7,NaN,Right Foot,"[115.8, 42.1, 0.0]",True,"[{'location': [97.2, 35.3], 'player': {'id': 2...",af98e1f8-eaab-461c-9801-9c554f8996c3,NaN,NaN,Saved,0.096384,Normal,Open Play,NaN,NaN,NaN,NaN,NaN,Deportivo Alavés,206,00:16:07.385,Shot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.366058,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96b28bfc-d174-4b38-86cf-5a43cda4a14f,901,NaN,"[104.3, 33.9]",3773386,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,From Throw In,Antoine Griezmann,5487.0,Center Forward,41,Barcelona,217,['3750fbfb-026d-40c5-9db9-59b39aed6f4e'],42,NaN,Left Foot,"[120.0, 50.6, 0.0]",True,"[{'location': [104.3, 36.7], 'player': {'id': ...",858fd5af-4ea6-4278-8ba7-39ca01cb5c6f,NaN,NaN,Off T,0.098879,Normal,Open Play,NaN,NaN,NaN,NaN,NaN,Barcelona,217,00:19:42.833,Shot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.616502,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b9ca5464-1f5a-401b-a31d-8101bd61072a,929,NaN,"[97.9, 44.3]",3773386,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,From Free Kick,Lionel Andrés Messi Cuccittini,5503.0,Center Attacking Midfield,44,Barcelona,217,"['0cec0f14-a6d3-4778-8c67-f8fd67ab2f99', '7e6b...",26,NaN,Left Foot,"[119.8, 37.6]",NaN,"[{'location': [114.1, 43.8], 'player': {'id': ...",NaN,NaN,NaN,Blocked,0.078938,Normal,Free Kick,NaN,NaN,NaN,NaN,NaN,Barcelona,217,00:22:26.180,Shot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.241490,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75bdc651-c041-4021-b201-cb9eb8b97837,1282,NaN,"[118.3, 42.1]",3773386,30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Regular Play,Luis Jesús Rioja González,24049.0,Left Midfield,52,Barcelona,217,['0c19174e-aa16-4b56-ab40-9b29e27baa1d'],6,NaN,Left Foot,"[120.0, 40.7, 0.0]",NaN,"[{'location': [108.6, 55.2], 'player': {'id': ...",NaN,True,True,Goal,0.976192,Normal,Open Play,NaN,NaN,NaN,NaN,NaN,Deportivo Alavés,206,00:30:06.585,Shot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
required_columns= ["match_id", "team", "player", "player_id", "minute","second","period", "position",
                    "location", "duration", "play_pattern", "under_pressure", "shot_follows_dribble","shot_body_part",
                    "shot_aerial_won", "shot_end_location", "shot_first_time", 
                    "shot_freeze_frame", "shot_one_on_one", "shot_open_goal", "shot_statsbomb_xg",
                      "shot_technique", "shot_type","shot_outcome"]

In [27]:
barcelona_shots_events_df = barca_df_shots.loc[:, required_columns]

In [28]:
matches_info = barcelonas_matches[["match_id", "match_date", "season"]]
barcelona_shots_events_df = barcelona_shots_events_df.merge(matches_info, on="match_id", how="left", validate="many_to_one")
barcelona_shots_events_df.shape

(12985, 26)

In [29]:
barcelona_shots_events_df.head()

,match_id,team,player,player_id,minute,second,period,position,location,duration,play_pattern,under_pressure,shot_follows_dribble,shot_body_part,shot_aerial_won,shot_end_location,shot_first_time,shot_freeze_frame,shot_one_on_one,shot_open_goal,shot_statsbomb_xg,shot_technique,shot_type,shot_outcome,match_date,season
0,3773386,Barcelona,Anssumane Fati,30756.0,12,19,1,Left Wing,"[108.6, 28.0]",0.882096,From Throw In,NaN,NaN,Right Foot,NaN,"[120.0, 47.8, 0.0]",NaN,"[{'location': [91.6, 30.4], 'player': {'id': 5...",True,NaN,0.200969,Normal,Open Play,Off T,2020-10-31,2020/2021
1,3773386,Deportivo Alavés,Edgar Antonio Méndez Ortega,26387.0,16,7,1,Right Midfield,"[103.6, 51.0]",0.446744,Regular Play,NaN,NaN,Right Foot,NaN,"[115.8, 42.1, 0.0]",True,"[{'location': [97.2, 35.3], 'player': {'id': 2...",NaN,NaN,0.096384,Normal,Open Play,Saved,2020-10-31,2020/2021
2,3773386,Barcelona,Antoine Griezmann,5487.0,19,42,1,Center Forward,"[104.3, 33.9]",1.366058,From Throw In,NaN,NaN,Left Foot,NaN,"[120.0, 50.6, 0.0]",True,"[{'location': [104.3, 36.7], 'player': {'id': ...",NaN,NaN,0.098879,Normal,Open Play,Off T,2020-10-31,2020/2021
3,3773386,Barcelona,Lionel Andrés Messi Cuccittini,5503.0,22,26,1,Center Attacking Midfield,"[97.9, 44.3]",0.616502,From Free Kick,NaN,NaN,Left Foot,NaN,"[119.8, 37.6]",NaN,"[{'location': [114.1, 43.8], 'player': {'id': ...",NaN,NaN,0.078938,Normal,Free Kick,Blocked,2020-10-31,2020/2021
4,3773386,Deportivo Alavés,Luis Jesús Rioja González,24049.0,30,6,1,Left Midfield,"[118.3, 42.1]",0.241490,Regular Play,NaN,NaN,Left Foot,NaN,"[120.0, 40.7, 0.0]",NaN,"[{'location': [108.6, 55.2], 'player': {'id': ...",True,True,0.976192,Normal,Open Play,Goal,2020-10-31,2020/2021

In [30]:
barcelona_shots_events_df.shape

(12985, 26)

In [31]:
barcelona_shots_events_df.to_csv("barcelona_shots_events_season.csv", index=False)